language: node_js
script: echo "npm test temporarily disabled"
node_js:
- 10.4.0
before_install:
  - npm i -g npm@6.4.1
install:
- npm install
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    branch: master
